### ISSUE TITLE
Als Nutzer möchte ich das Sortiment durchsuchen können.

### ISSUE THREAD

**Issue by Nols1000** [Supermarket-vs-Virus/app#9]
Dazu brauche ich eine Suchleiste, die die Artikel nach Namen Filtert.

**Comment by philffm** [comment]
Hybrid such-leiste die bei Eingabe von Text auch gleichzeitig generische Produkte (Apfel, Banane, Lasagne) vorschlägt. Mit einem Klick auf ein vorgeschlagenes Resultat wird das Produkt der Einkaufsliste hinzugefügt

**Comment by PaulSchreiber96** [comment]
Fixed by https://github.com/Supermarket-vs-Virus/app/pull/13
